### ISSUE TITLE
Encouraging Live Coding

### ISSUE THREAD

**Issue by ChrisOwen101** [CodeYourFuture/syllabus#172]
**What is the hypothesis?**

Historically, I've leaned away from Live Coding as a preferred way of teaching - however after some conversations with volunteers and seeing how other organisation teach it as a skill I'm being convinced by it.

I'd like to experiment with how we could involve 'Live-codable' exercises into the Syllabus that are easy for a volunteer to read, comprehend and deliver with limited experience of Live Coding. 

**Why is this important?**

Delivering our content in a good way is an important part of what we do at CodeYourFuture.

**Supporting Resources**

https://carpentries.github.io/instructor-training/14-live/

**Comment by 40thieves** [comment]
Couple of thoughts from me:

- I would suggest that we make live-coding training (& practice?) strongly recommended for new teachers. I do think there are quite a few pitfalls that make it difficult to do well. This does also make it somewhat difficult to design the syllabus around: how do we write lessons with live-coding in mind, while keeping it optional?
- A solution to this might be to make live-coding in the lesson highly structured. This is kind of what I aim for in the React module: since each example is in a CodeSandbox, I can experiment with the code to answer questions/explain things in more depth
- Having said that, I think there are some opportunities for less structured live-coding. E.g. mid-week calls led by volunteers. This is also a less pressured environment in which to practice
