### ISSUE TITLE
Scotland fundamentals revamp - new syllabus branch?

### ISSUE THREAD

**Issue by zero-point** [CodeYourFuture/syllabus#188]
**What is the hypothesis?**
Edu and PD teams want a different approach to Fundamentals that would ease people in and volunteers want the ability to adapt it and yet have a single source for the syllabus. Module leaders suspect this would be an issue later on in the course as well, as they evaluate their respective modules. The idea would be to create a separate branch for the whole syllabus.

**Why is this important?**
- allow input from volunteers teaching the course
- adapt to specific local needs
- prevent sharing two or more syllabus sources throughout the course

**Supporting Resources**

**Comment by anthonygerrardlrng** [comment]
[Fundamentals Assessment.pdf](https://github.com/CodeYourFuture/syllabus/files/6074568/Fundamentals.Assessment.pdf)

**Comment by alastair87** [comment]
Some thoughts, following on from Anthony's points:

The structure of the text puts a lot on one page, sometimes on one screen (depending on the screen size) and this may be overwhelming and confusing for students. It emphasises the amount of work to be done and also possibly will encourage drift onto one task before completing what they are working on.

We need to establish what technologies the Scotland class is going to use (e.g. Google Classroom or not) since this will also mean amending the material.

We'd need to expose the Scotland branch of Fundamentals to trainees - e.g. fundamentals-scotland.codeyourfuture.io. I assume this is just a minor configuration matter.

**Comment by ChrisOwen101** [comment]
Thanks so much for the above comments - I really appreciate it. 

My initial thoughts for this would be that we improve the current Fundamentals course rather than branching off the current syllabus. Nothing in here is fixed or permanent, it changes slightly and is improves each time we run it and it seems like a good selection of the issues that you raised could be fixed by providing better support in our current Master Syllabus rather than branching onto a new one - this way all schools can benefit from the work put into the Scotland branch! 

Looking forward to talking about it this evening

**Comment by alastair87** [comment]
Khan Academy material:

It might be confusing because it's using JavaScript to draw and animate things, whereas we initially use JS just for data handling in the rest of the course and start off by learning to 'draw' the page with HTML/CSS.

It introduces a lot quickly, after showing a few function calls, it then goes straight on to assigning functions to variables. Before we know it we are even doing mouse interaction (in a simplified way).

There is *definitely* too much for them to attempt in a day or possibly even in a week without regular contact. A lot of trainees will probably find it frustrating. If we do use the material, suggest being selective and following up fairly quickly with live coding walkthrough (trainee-guided) so that frustration doesn't build.

Alternative could be to show them the building blocks of a very simple CLI application (along the lines of "What is your name?", repeat it back etc). This might give them a better idea of what we start using JavaScript for.
