### ISSUE TITLE
Clear up old versions of Syllabus

### ISSUE THREAD

**Issue by SallyMcGrath** [CodeYourFuture/syllabus#578]
Versions of our syllabus are published all over the place. I don't know all the places.

- [x] https://github.com/CodeYourFuture/syllabus-master / https://codeyourfuture.github.io/syllabus-master/
- [x] https://github.com/CodeYourFuture/syllabus-london / https://codeyourfuture.github.io/syllabus-london/
- [x] https://github.com/CodeYourFuture/syllabus-scotland / https://codeyourfuture.github.io/syllabus-scotland/

Let's try to clean this up and redirect to our live syllabus

**Comment by 40thieves** [comment]
There's https://github.com/CodeYourFuture/syllabus-scotland / https://codeyourfuture.github.io/syllabus-scotland/ too, but I'm 99% that's all of them.

> redirect to our live syllabus

Need to test this, but https://dev.to/steveblue/setup-a-redirect-on-github-pages-1ok7 looks like it might work

> Let's try to clean this up

Assuming I can get the redirects working, I can go ahead and mark them as archived.

**Comment by 40thieves** [comment]
I ended up setting up a couple of tests to see what Github Pages does under different circumstances.

I wasn't sure what happens if you archive the underlying repo. Archived repo: https://github.com/40thieves/archive-test / Page for the archived repo: https://40thieves.github.io/archive-test/. It seems like the page is still live.

And I wanted to try the redirect method suggested in the link above. Redirecting repo: https://github.com/40thieves/redirect-test / Page for the redirecting repo: https://40thieves.github.io/redirect-test/. It does indeed seem to work.

So I think the best option for us here is to:

1. Modify the `index.html` to redirect to the new syllabus
2. Archive the repo
