### ISSUE TITLE
Add Array Destructuring to JS3-3 and Remove Classes

### ISSUE THREAD

**Issue by ChrisOwen101** [CodeYourFuture/syllabus#6]
**Which module(s) and week(s) does this change effect?**
Module: JavaScript Core 3
Week 3

**What is the work that needs to be done?**

Removing Classes
1. Remove content about `Class`es from JS3-3
2. Remove content about `Class`es from JS3-3 homework

Adding Array Destructuring
1. Write content that properly explain the usages of array destructing and why it will be helpful.
2. Write several in-class exercises which teach the students how to use array destructuring (consider using [Faded Examples](https://www.researchgate.net/figure/Sample-faded-worked-example_fig2_282434634))
3. Add homework tasks that ask the student to write some array destructuring code
4. Add homework tasks that ask the student to convert existing code to using array destructuring

**Why is this work important to do?**

React has now moved from using classes to using `hooks` which means that JS Classes now have far less importance in our course. For this reason we should update our curriculum so that our students are better prepared for React.

**Additional context**

**Who might need to know about this change?**

@ChrisOwen101

**Comment by 40thieves** [comment]
This also has down-stream effects on React as we did have a (short) section when teaching `useState` to cover destructuring. See the bottom of [this section](https://syllabus.codeyourfuture.io/react/week-2/lesson#using-usestate).

It's on my list to remove this section (because we decided to move it earlier, as discussed here). I'll coordinate with @ChrisOwen101, so that we don't accidentally drop it for a class.

**Comment by 40thieves** [comment]
Update: I've left the link to the Wes Bos post about destructuring in my [React update PR](https://github.com/CodeYourFuture/syllabus/pull/36), so that Birmingham can include it there. The section is somewhat light on the concept - the idea was to rely on the post for the content, to try keep the focus on React.

The consensus from the London post-module retro was that it would be better to do more practice of the concept in isolation, before combining with `useState`.

Looking at it again now, I think I'd be in favour of keeping some recap of the concept in the React module. But I'll hold off on making that change until this one is decided upon.

**Comment by nbogie** [comment]
@40thieves yeah it would be good to keep relevant recap material for JS pre-reqs linked in the relevant spot in react module, and to leave it to the discretion of the city teachers to gauge whether it is needed in their particular case.
