### ISSUE TITLE
Create Git Lesson for the beginning of the course

### ISSUE THREAD

**Issue by ChrisOwen101** [CodeYourFuture/syllabus#64]
**Which module(s) and week(s) does this change effect?**
Module(s): Git
Week(s): 1

**What is the work that needs to be done?**

This year, we're going to dedicate a full day to working on `Git` & `Git Command Line` OR `Github Desktop`

By the end of the lesson a student should be able to

- define what Git is and what it does
- define what the differences between Git and Github are
- create a repository on Github
- clone a repository using Github Desktop or Command Line
- make changes to a repository using Github Desktop or Command Line
- create and move between branches using Github Desktop or Command Line

You are also welcome to add to the above list with any LOs that you think are important.

**Github Desktop vs Command Line**

Before you start working on this ticket we need to have a discussion on which method is best for us to teach.

We maybe also decide to design the lessons in such a way that we can leave it up to the school to define.

**Why is this work important to do?**

Git is one of the key tools we use to submit homework and historically has been tricky getting students setup with.

**Additional context**

We have a current workshop for Github Desktop [here](https://syllabus.codeyourfuture.io/workshops/git-desktop)

**Comment by illicitonion** [comment]
Extra possible LOs:
* Fetching from upstream so that they can pull in our updates
* Maybe resolving basic merge conflicts (maybe not)

**Comment by ChrisOwen101** [comment]
Loic to provide teaching content that was used to in Scotland.

**Comment by mickyginger** [comment]
At General Assembly we did 1 half day on git on the command line... We expected the students to pick up the basics through repetition, since they were submitting homework every day. We also provided a cheatsheet PDF of the steps they needed to take to submit their homework.

**Comment by illicitonion** [comment]
Vague action items:
* Teach github desktop in a full day, with worked examples.
* Introduce a class before or after JS3 to teach the terminal (`cd`, `ls`, `pwd`, `npm`), and potentially introductory `git` (`clone`, `add`, `commit`, `status`, `log`).
* Maybe split homework (at least for JS1) modules into per-week rather than per-module, to avoid the impact of messing up branches or needing to fetch upstream.

* Add a "Work with someone else on separate branches" lesson maybe in JS3 or Node, to teach branches.

* Work out how to do the above without adding 3 weeks to the course.

**Comment by illicitonion** [comment]
Concrete action items:
* 4 hours teaching git theory, and enough Github Desktop for learners to be able to submit homework (**no branches**)
* Plan to (but not necessarily this week) have a 2 hour class later in the course to introduce the terminal, including `git` as an example command line tool.

We'll work out what to do about branches and working together in the future.

**Comment by illicitonion** [comment]
I've started putting this together - there's a rough structure, with the first few sections fleshed out rendered at https://github.com/illicitonion/syllabus/blob/git/docs/git/index.md

I very enthusiastically welcome feedback on the approach, structure, and in particular the learning objectives. Happy to have that discussion on this issue, or as comments on https://github.com/CodeYourFuture/syllabus/pull/100/files. It's definitely a draft, so let's try to keep to overall comments rather than wording nit-picks for now :)

Note that the LOs are pretty different from those in the initial issue description, after discussion in the syllabus team meeting this week. In particular I have dropped:

* create a repository on Github
* create and move between branches using Github Desktop or Command Line

reframed the others explicitly in terms of homework rather than abstract git concepts, and added a LO around exploring history.

I'll keep fleshing this out over the weekend.

/cc @40thieves @mickyginger @ChrisOwen101

**Comment by illicitonion** [comment]
Ok, the links in the previous comment have a first draft of what this could look like (riddled with TODOs). Please take a look, and give any feedback that comes to mind!

I can be available Monday or Tuesday night for a call, if anyone wants to have a more in-depth chat about it, or work on fleshing it out together :)

**Comment by ChrisOwen101** [comment]
**Idea for Homework**

1. Git It - https://github.com/jlord/git-it-electron - 3 Hours
Download, Install and Complete that program. It'll walk you through setting up Git on your laptop and an introduce to Git Command Line.
2. First Day on Github - https://lab.github.com/githubtraining/first-day-on-github - 3 Hours
Complete this course on Github Basics
3. Watch this "Intro To Github Desktop" Video - https://www.youtube.com/watch?v=77W2JSL7-r8 - 20 Minutes

**Comment by 40thieves** [comment]
Thanks for making a start on this @illicitonion! I've left some comments on your PR (process point - I would have thought that you have permissions to make PRs directly against the upstream CYF repo? If not, I can take a look). Happy to discuss next week 👍

**Comment by nbogie** [comment]
Looking good!

One thing we might consider is how / if we intend to support the students once they're off the happy path: purely by support calls, or by having them practice those other paths.  The latter is hard to do, but derailments are  frequent and often significant disturbances (before even accounting for the damage to confidence that's less immediately obvious).

---

>  "Imagine your teacher wanted everyone in the class to answer three questions and to send back the answers. What capabilities would we need in order to be able to do that?"  
Playing devil's advocate for a minute: some students will reasonably hear this and initially think - well we have perfectly good technologies already for that: how about Email? or Slack?

---

Some students will have experience with version control in google docs, and office products ("track changes")

---


It might help to contemplate designing the class firstly as an introduction to a persistent, concise reference (guide/cheatsheet/recipe book) - created or curated -  so that:

1: the student becomes familiar enough with the reference ("it exists, I know where, I know its basic value to me, I am not scared of it") that they will willingly refer back to it in future when they forget homework submission steps, rather than try to read all the way through the full class content each time to find one invocation or four steps.

2: at later points in the course, the syllabus and teachers can simply link to that reference, linking to, for example, the homework submission process.

3: follow-on classes can build around the same heart as necessary.

At least, I would suggest adding an objective (stated to the students or not) along the lines of: By the end of the class the student should know the one place to look for information when they forget everything else this lesson attempted to teach them.
(Else that place is going to be youtube, which really doesn't work too well with git, particularly if we're teaching github desktop.)

---
